name: build-and-push

on:
  push:
    branches:
      - 'trunk'
permissions:
      id-token: write    # Required for aws role assumption
      contents: write    # This is required for actions/checkout@v1
jobs:
  docker:
    runs-on: "ubuntu-latest" # will have to rename
    steps:
      -
        name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders
      -
        name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.SERVER_NAME }} #configures env fro docker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.SERVER_NAME }}/${{ secrets.DOCKER_REPO }}/my_container_name:${{ github.run_number }}
